Book.create!([
  {bookshelf_id: 1, title: "The Math Book", author: "Clifford A. Pickover", google_id: "JrslMKTgSZwC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks3.books.google.com/books?id=JrslMKTgSZwC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72MOPlRMRzApdI9-PBj62RPJCXJTJDApqZXcdc-WcvmOuauyqTPg8-cFCh__MaN5zojrZUGsUuUS9C1QyP02syny5i0hDC4wY1kg6eFYPMZPOqV2Xk&source=gbs_api", thumbnail: "http://bks3.books.google.com/books?id=JrslMKTgSZwC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70N6a8HOf4YpsRNH9-m3p7QGCOe4YeCeLiYC0G8wt8N4RGf4y4JfGg8B2kYO0Kt_-a3IRwe9JBY6ru1YXekUZ9PzbHLmgTcbtREFEjUz2k5ahi0dxY&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/JrslMKTgSZwC"},
  {bookshelf_id: 1, title: "Math", author: "Marilyn Burns", google_id: "dAE_Ewwz1TsC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks2.books.google.com/books?id=dAE_Ewwz1TsC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE70vfdtDzgcGUzc8Hj7RRS71wQeHOKbrF1sawsPiMNLpMSYs39yXnT8UclsQeMrfAQrfebEXnb7psIhFL5HAmTjKNSrVoZJIQ0vwLB31uhCC02L_AgI&source=gbs_api", thumbnail: "http://bks2.books.google.com/books?id=dAE_Ewwz1TsC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71lylyWhdTZ0aLgaSxnksMNB0n8YbCyk6lRVYDvHS-jH3iTfCYcXiB44RyU4Kj3klp0qVfLmvVyfMoMPuio1SqFMLyRG9Ho_JoCMc9H8A_63nUCEGw&source=gbs_api", self_link: nil},
  {bookshelf_id: 2, title: "Miette", author: "Meg Ray", google_id: "Paefqk3kgewC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks2.books.google.com/books?id=Paefqk3kgewC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72PDQmS1GawyldjgurWp57S2r72XqbImIa5Pt7ir4SlFaIZh60HJeUCyEC2v1F-_WAI2fJd6n-8cLaazMOTs1NmVNZDkYXFPtjBhpKxhEvQ6Yg8wts&source=gbs_api", thumbnail: "http://bks2.books.google.com/books?id=Paefqk3kgewC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71BaDUGbMOiMPjgDDiuxVQhbjtEAhX54gxZZ_-jcg_ra6s1wVYVeyH-ddtDEB8EOYuIVSfTeS_BzqPHtSBaVwNS3FPTJlOv6WzNGg_8G-KkFokTVUE&source=gbs_api", self_link: nil},
  {bookshelf_id: 2, title: "Plating for Gold", author: "Tish Boyle", google_id: "Ro3_xQ86qxMC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks8.books.google.com/books?id=Ro3_xQ86qxMC&printsec=frontcover&img=1&zoom=5&imgtk=AFLRE70Gw9KPAnvoscIFxtgm3GSy2ON4nh3GlrTv3WFircRHFS4lQE8VS_udjnxMBjROERqwqf3cM0qD4V3lUGmGwg3MC-sJMrBOzYjIo5KmHXZid7Pfxj4&source=gbs_api", thumbnail: "http://bks8.books.google.com/books?id=Ro3_xQ86qxMC&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70cCuCZ0oOfBN-wf06OEgL9MzJskkWmeakhl1K6SheLaOCcAtaengt8yAHBXJp8FeExmnz6dGuiWyqp3QA_eJhwxmhOpvnjBTIFV4XMfZqgNU1-r-I&source=gbs_api", self_link: nil},
  {bookshelf_id: 2, title: "Espresso Coffee", author: "Andrea Illy", google_id: "AJdlfSFCmVIC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks9.books.google.com/books?id=AJdlfSFCmVIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks9.books.google.com/books?id=AJdlfSFCmVIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/AJdlfSFCmVIC"},
  {bookshelf_id: 3, title: "The Influence of Sea Power Upon History, 1660-1783", author: "Alfred Thayer Mahan", google_id: "zBYLAAAAYAAJ", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks8.books.google.com/books?id=zBYLAAAAYAAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks8.books.google.com/books?id=zBYLAAAAYAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/zBYLAAAAYAAJ"},
  {bookshelf_id: 2, title: "The Coffee Book", author: "Nina Luttinger", google_id: "jP99B9uAdv4C", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks6.books.google.com/books?id=jP99B9uAdv4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks6.books.google.com/books?id=jP99B9uAdv4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/jP99B9uAdv4C"},
  {bookshelf_id: 2, title: "Coffee", author: "Kenneth Davids", google_id: "fYnWAAAAQBAJ", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks8.books.google.com/books?id=fYnWAAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks8.books.google.com/books?id=fYnWAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/fYnWAAAAQBAJ"},
  {bookshelf_id: 2, title: "I Love Coffee!", author: "Susan Zimmer", google_id: "DZEIxKxX-rQC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks1.books.google.com/books?id=DZEIxKxX-rQC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks1.books.google.com/books?id=DZEIxKxX-rQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/DZEIxKxX-rQC"},
  {bookshelf_id: 2, title: "Chinese Coffee", author: "Ira Lewis", google_id: "iB8fPDAXeLYC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks9.books.google.com/books?id=iB8fPDAXeLYC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks9.books.google.com/books?id=iB8fPDAXeLYC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/iB8fPDAXeLYC"},
  {bookshelf_id: 1, title: "A Classical Introduction to Modern Number Theory", author: "Kenneth Ireland", google_id: "jhAXHuP2y04C", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks2.books.google.com/books?id=jhAXHuP2y04C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks2.books.google.com/books?id=jhAXHuP2y04C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/jhAXHuP2y04C"},
  {bookshelf_id: 1, title: "Advanced Number Theory", author: "Harvey Cohn", google_id: "yMGeElJ8M0wC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks5.books.google.com/books?id=yMGeElJ8M0wC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks5.books.google.com/books?id=yMGeElJ8M0wC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/yMGeElJ8M0wC"},
  {bookshelf_id: 1, title: "Lectures on Number Theory", author: "Peter Gustav Lejeune Dirichlet", google_id: "8h8aWmnp1k8C", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks2.books.google.com/books?id=8h8aWmnp1k8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks2.books.google.com/books?id=8h8aWmnp1k8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/8h8aWmnp1k8C"},
  {bookshelf_id: 6, title: "Resident Evil: Extinction", author: "Keith R. A. DeCandido", google_id: "qSVVSawysA8C", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks7.books.google.com/books?id=qSVVSawysA8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks7.books.google.com/books?id=qSVVSawysA8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/qSVVSawysA8C"},
  {bookshelf_id: 6, title: "Genetics: A Conceptual Approach", author: "Benjamin A. Pierce", google_id: "z4pXRaZAkdkC", rating: nil, reading_status: nil, review: nil, thumbnail_small: "http://bks2.books.google.com/books?id=z4pXRaZAkdkC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api", thumbnail: "http://bks2.books.google.com/books?id=z4pXRaZAkdkC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", self_link: "https://www.googleapis.com/books/v1/volumes/z4pXRaZAkdkC"}
])
Bookshelf.create!([
  {user_id: 1, name: "Math", rank: 1},
  {user_id: 1, name: "Cooking", rank: 2},
  {user_id: 1, name: "Naval History", rank: 3},
  {user_id: 4, name: "Time Travel", rank: 1},
  {user_id: 4, name: "Roman History", rank: 2},
  {user_id: 1, name: "Genetics", rank: 4}
])
Friendship.create!([
  {source_friend: 1, dest_friend: 2},
  {source_friend: 2, dest_friend: 1},
  {source_friend: 4, dest_friend: 5},
  {source_friend: 5, dest_friend: 4},
  {source_friend: 3, dest_friend: 5},
  {source_friend: 5, dest_friend: 3},
  {source_friend: 2, dest_friend: 5},
  {source_friend: 5, dest_friend: 2}
])
User.create!([
  {email: "bob@swift.com", password_digest: "$2a$10$FfhLdy9cj1bbK438gqv6a.RtrzqhhsenIW8nn9flBh.kveAviiyVW", session_token: "b232abfcb9952c2353546a2526e9860b", account_status: "N", omniauthable: nil},
  {email: "eve@swift.com", password_digest: "$2a$10$YeVCWVcuNLoMPyRIOXC11.x8NrBQ7Mdx8Px/27Gs.Bhr/dPBuubZi", session_token: "2c6112e4f6691dd3a28308ddbb55a627", account_status: "N", omniauthable: nil},
  {email: "amy@tardis.com", password_digest: "$2a$10$YnjoHFCvNhK15CWe9ZLtf.eVQqt8r4XrSuC5/dikYAwWiGTEfEQb.", session_token: "67c04e789acb09055aa948a7727eb8c8", account_status: "N", omniauthable: nil},
  {email: "rory@taris.com", password_digest: "$2a$10$pizNrqBNdVrkluIrV/KcvehFkjSco9HvfS7uYLNs51asceJjAtgXO", session_token: "4f568186342c227909e426c2c95b43e4", account_status: "N", omniauthable: nil},
  {email: "alice@swift.com", password_digest: "$2a$10$DJQ4TiN4pbcPFqoD4Kxb9OvNWB5WcLKgzGbSlXBZjywBSUgLxbwhi", session_token: "8845d82cb089a9169a939ced4598ba32", account_status: "N", omniauthable: nil}
])
